### ISSUE TITLE
Autoscroll the log

### ISSUE THREAD

**Issue by frosch95** [rladstaetter/LogoRRR#112]
I use LogoRRR as "tail -f" and would love to have an autoscroll option.

Kubernetes Lens has a nice way to support auto scroll:
* When the scroll bar is at the bottom, auto scroll is enabled. 
* When the scroll bar is draged by the user, the auto scroll is disabled. 

Maybe it is easier to have a checkbox if autoscroll is enabled or disabled.

**Comment by rladstaetter** [comment]
That's a great idea!

Actually the 'tail -f' - let's call it 'autoscroll' mode - for LogoRRR needs more/some love - #61 for example points in the direction you proposed. I think a checkbox which enables/disables an autoscroll mode is the way to go since it is s easier to implement 😇.

If the checkbox is activated, it will track file changes for the given log file and follow the most current output.
