### ISSUE TITLE
Select text with mouse-drag and copy 

### ISSUE THREAD

**Issue by orx0815** [rladstaetter/LogoRRR#242]
Amazing tool to browse big logfiles.

However when I've found lines-of-interest, I can't copy-paste them into a ticket.
Have to use the 'copy current selection' into a text-editor and remove unwanted lines.
Just mark them with the mouse and Ctrl+C  would be much nicer.

Related but not so important:
When I use the 'Ignore entries above/below', there is no way back, is it?

**Comment by rladstaetter** [comment]
Yes, the "export text" functionality is something I'm not really happy about. I have to see how to implement it.

**Comment by rladstaetter** [comment]
Undo feature will be tracked in #243

**Comment by rladstaetter** [comment]
It turns out that this was a low hanging fruit! 

<img width="708" alt="image" src="https://github.com/user-attachments/assets/2e6ad5ad-a1f3-43ab-acc1-7681b0643e86">

Starting with the next release, you can use LogoRRR like you've used to - but by pressing `SHIFT` and mouseclick you can select multi lines, and with the context menu you can copy the highlighted text to the clipboard.

**Comment by rladstaetter** [comment]
Regarding the 'ignoring entries' feature: 

I rechecked with the latest release (24.4.0) -  "Ignore entries above/below" **is** reversible, you just have to activate/deactivate a filter, the selection will be reset. 

(another reason to write a manual #245 🤷🏼‍♂️ - i forgot this myself ...)
