### ISSUE TITLE
Support for modules (someip)

### ISSUE THREAD

**Issue by lanthale** [rladstaetter/LogoRRR#3]
Thank you for that tool. 

Two features would be great to have:
- Apply/define filters for custom events with colors 
- Support for modules or a some sort of decryptio module. E.g. decrypt all someip messages before loading the logfile

**Comment by rladstaetter** [comment]
Thank you for opening the first issue here ;-)

I'll definitely want to add a custom search functionality, maybe even for the next release. 👍 

As for the second part of your feature request you would have to elaborate further. Modules in which sense? 

Concerning decryption: I think that decrypting logfiles/messages should be done in another application, as its highly specific to your usecase/encryption algorithm. Maybe it could be included with some sort of generic plugin / interface system, but still this would just complicate things. I try to keep the tool as simple as possible 🤷‍♂️

**Comment by rladstaetter** [comment]
added basic search functionality just now ...

**Comment by rladstaetter** [comment]
at least the first part of your issue description should be implemented with release 21.2.1 - i would like to close this issue since i have no plans to include decryption or modularizing the application since I don't have any hopes that this will be possible soon with Scala nor do I have the expertise to do it - maybe you can point me to relevant documentation? the last time i've tried I had to give up unfortunately ...

**Comment by rladstaetter** [comment]
closing issue if you don't mind ...

**Comment by lanthale** [comment]
Thank you for the implementation. Regarding someip the only documentation is https://www.autosar.org/fileadmin/user_upload/standards/foundation/1-0/AUTOSAR_PRS_SOMEIPProtocol.pdf. But this is very special. Maybe I will try to implement a someip parser and later on integrate into your project if you want.
