### ISSUE TITLE
Regular expression

### ISSUE THREAD

**Issue by austinhuang0131** [rladstaetter/LogoRRR#60]
Would it be possible for the filter to support searching by regular expression?

**Comment by rladstaetter** [comment]
of course. this is perfectly possible. 

the reason it is not already implemented is that i wanted to keep the app very approachable and don't want to overload the application with features. 

i personally never use 'advanced' search, i always end up using simple text searches. nevertheless, i would propose there are - one day - two modes of LogoRRR, one 'basic' view and then a more 'sophisticated' view which would contain search via regex, too. the next few milestones i'm trying to exploit time information from log lines and will concentrate on visualisation thereof (like for example #12 or #43 ...). But since I try to prioritize user requests i'll include this in milestone 22.2.0.

**Comment by rladstaetter** [comment]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/119250/183264745-b98d468c-c5f9-46e4-9c65-7c8a81f0215c.png">

Implemented regular expression search, with following features:  
- You can switch between normal text search and regular expression search via a new button (see screenshot).
- Regular expression search can be activated via a keyboard shortcut (CTRL-R on windows, CMD-R on mac).  
- Every regex will be matched against a single line

Known limitations are:

- no highlighting of matches (unlike simple text search where hits are highlighted)
- between program invocations regular expression searches will be converted to simple text searches and thus won't work anymore. 

But for Release 22.2.0 I'll go with this implementation and close this issue.
